Step method should behave like @step
gridgain/tiden pull request #17
Opened 2020-10-19 12:15 UTC by pilshchikov

`with Step():` can't work with embedded classes like @step, its needs to be fixed.

In all tests classes, we hold `_secret_report_storage` to store and add report data during a test run.
@step get this data from test class and modify this private parameter, but if we create an instance of any app this class didn't contain this storage.
That's why we set test class as an additional argument `_parent_cls` in any app instance which needs to be described with @step report.
For a long time, @step can work with these embedded apps, but `Step` don't. And now time to fix this.

2020-10-19 16:13 UTC, mshonichev requested changes

2020-10-19 16:13 UTC, mshonichev commented on src/tiden/report/steps.py
> +        elif getattr(self.cls, '_parent_cls', None) and getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None):
Are we sure that nest is limited by only two levels deep here? E.g. what if we would have `A -> (parent_cls) -> B -> (parent_cls) -> C (GeneralTestCase)` ?

2020-10-19 16:13 UTC, mshonichev commented on src/tiden/report/steps.py
> +            report = getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None)
pls, move `parent_cls = ...` before this line and reuse `parent_cls` here. would be more readable.

2020-10-19 16:13 UTC, mshonichev commented on src/tiden/report/steps.py
> +            report.end_step(self.unique, 'passed' if step_result else 'failed',
I would like to see `end_step` arguments generation logic be extracted in order to not duplicate here.

2020-10-19 16:13 UTC, mshonichev commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
same as above, move up, use `parent_cls` in the expressions instead of constantly typing `getattr(self.cls, '_parent_cls')`

2020-10-19 22:34 UTC, pilshchikov commented on src/tiden/report/steps.py
> +        elif getattr(self.cls, '_parent_cls', None) and getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None):
When we will, then we made it

2020-10-19 22:35 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            report = getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None)
I'm not sure
`parent_cls` used only on the next line after the declaration
no need to move it in the start

2020-10-19 22:43 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            report.end_step(self.unique, 'passed' if step_result else 'failed',
Moved all parameters calculation above if-else code, now looks clean

2020-10-19 22:56 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
Moved all parameters calculation above if-else code, now looks clean

2020-10-19 22:59 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
I can not save this thing between start step and the end because inside step can be some other step which is changed storage and saved data can be different

2020-10-20 11:02 UTC, mshonichev commented on src/tiden/report/steps.py
> +        elif getattr(self.cls, '_parent_cls', None) and getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None):
The `ControlUtility` comes into my mind, actually. 

Because of nest limited to 1, we had to do this in the `Ignite` constructor:
```
self._cu = ControlUtility(self, parent_cls=self._parent_cls)
```

Do you think if it's ok or better use more generic method not bound by one lvl nest?

2020-10-20 11:03 UTC, mshonichev commented on src/tiden/report/steps.py
> +            report = getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None)
well, I thought that as you define it anyway, then reuse it instead of duplicating `getattr` thing would make this slightly more readable.

2020-10-20 11:07 UTC, mshonichev commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
you mean inside `.end_step()`. Wow, that side effect really deserves a commentary then

2020-10-20 11:07 UTC, mshonichev commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
but actually I've meant pulling up this code:
```
self.unique, 'passed' if step_result else 'failed',
                            self.stacktrace[:5000] if self.status is not None else format_exc()[:5000])	                            
```
to some well commented protected method so that logic at least had a name in the name of readability

2020-10-20 12:11 UTC, pilshchikov commented on src/tiden/report/steps.py
> +        elif getattr(self.cls, '_parent_cls', None) and getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None):
Remember now, yeah, we have this embedded classes already

2020-10-28 21:02 UTC, pilshchikov commented on src/tiden/report/steps.py
> +        elif getattr(self.cls, '_parent_cls', None) and getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None):
done

2020-10-28 21:02 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            report = getattr(getattr(self.cls, '_parent_cls'), '_secret_report_storage', None)
done

2020-10-28 21:02 UTC, pilshchikov commented on src/tiden/report/steps.py
> +            parent_cls = getattr(self.cls, '_parent_cls')
done

2020-10-28 21:04 UTC, pilshchikov commented
- Added embedded storage change method
- Added tests for steps
- With new tests found bugs which are were fixed

2020-11-02 05:23 UTC, mshonichev approved these changes
LGTM!

2020-11-02 15:38 UTC, merged