Add build args in dockermanager.build_image method
gridgain/tiden pull request #18
Opened 2020-10-19 20:33 UTC by pilshchikov

- Add `--build-args` in `dockermanager.build_image`
- Refactor string.format to f-string
- Remove hard codded DNS in `dockermanager.create_service`

2020-10-19 20:53 UTC, MaxLosevskoy commented
Kudos for f'{}' formatting

2020-10-20 00:13 UTC, mshonichev requested changes

2020-10-20 00:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +        cmd = f"docker build -t {name} {params} {build_directory} 2>&1 {self.config['rt']['remote']['test_dir']}/build_{name}.log"
Docker sends all files in the current directory to the daemon as build context when building the image. If we don't control the context, it can accidentally be very big, e.g. if the current directory is the `work` or `var`.

I would suggest considering change to either build or dockerfile directory.

2020-10-20 00:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +            image = f"{image_name}:{kwargs['tag']}"
consider putting `':latest'` if `tag` is None

2020-10-20 00:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +                param.append(f"-v {local_dir}:{container_dir}")
Let's make 'container_dir' a variant: either a directory, or a tuple with directory and mount options. 
For example, `':ro'` or `':delegated'` are quite common options.

2020-10-20 00:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +        exec_cmd = f'docker exec {container_id} bash -c "{cmd}"'
There are some test crashes due to incorrect `container_id` got from previous commands. Let's assert its format with meaningful description here before boldly executing whatever stuff is injected into.

2020-10-20 09:37 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +        cmd = f"docker build -t {name} {params} {build_directory} 2>&1 {self.config['rt']['remote']['test_dir']}/build_{name}.log"
??? `build_directory` that's a build context, `dockerfile_path` that's a path to Dockerfile

2020-10-20 09:38 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +            image = f"{image_name}:{kwargs['tag']}"
done

2020-10-20 09:44 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +                param.append(f"-v {local_dir}:{container_dir}")
Nobody uses it, why we need to predict future usage. When someone will be needed for it, he made it.

2020-10-20 09:56 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +        exec_cmd = f'docker exec {container_id} bash -c "{cmd}"'
done

2020-10-20 10:04 UTC, MaxLosevskoy commented on src/tiden/dockermanager.py
> +        assert 'no such container' in output.lower(), f'Failed to find {container} to execute cmd: {cmd}'
I see the contradiction here - if the container wasn't found, `assert` passes. If **error** isn't there(and the container is probably **found**), we print 'Failed to find..'

@pilshchikov

2020-10-20 10:06 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +        assert 'no such container' in output.lower(), f'Failed to find {container} to execute cmd: {cmd}'
yes, thanks, fixed now

2020-10-20 11:12 UTC, mshonichev commented on src/tiden/dockermanager.py
> +        cmd = f"docker build -t {name} {params} {build_directory} 2>&1 {self.config['rt']['remote']['test_dir']}/build_{name}.log"
oh, my bad, I've totally forgot about that.

2020-10-20 11:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +                param.append(f"-v {local_dir}:{container_dir}")
experience with Sber shows that for better Mac performance using `':delegated'` for volumes is a must.

2020-10-20 11:13 UTC, mshonichev commented on src/tiden/dockermanager.py
> +                param.append(f"-v {local_dir}:{container_dir}")
keep in mind, we're making open source framework here, not our private tool.

2020-10-20 12:51 UTC, pilshchikov commented on src/tiden/dockermanager.py
> +                param.append(f"-v {local_dir}:{container_dir}")
done then

2020-10-20 13:01 UTC, mshonichev approved these changes
LGTM

2020-10-20 13:03 UTC, merged